apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: eda
  name: eda
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eda
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: eda
    spec:
      containers:
        - env:
            - name: GATEWAY_URL
              value: http://fastapi-app:8000
          image: eda
          imagePullPolicy: IfNotPresent
          name: eda
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 8010
              protocol: TCP
      restartPolicy: Always
