apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: eval
  name: eval
spec:
  ports:
    - name: "8030"
      port: 8030
      targetPort: 8030
  selector:
    io.kompose.service: eval
