apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: fastapi-app
  name: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fastapi-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: fastapi-app
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env-minio
          image: fastapi-app
          imagePullPolicy: IfNotPresent
          name: fastapi-service
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /code
              name: fastapi-app-claim0
      restartPolicy: Always
      volumes:
        - name: fastapi-app-claim0
          persistentVolumeClaim:
            claimName: fastapi-app-claim0
