apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: mlflow
            - name: POSTGRES_PASSWORD
              value: mlflow
            - name: POSTGRES_USER
              value: mlflow
          image: postgres:13
          name: postgres
          resources:
            requests:
              memory: "512Mi"
              cpu: "125m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 5432
              protocol: TCP
          # Liveness probe to check if the PostgreSQL process is running and responsive
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "PGUSER=${POSTGRES_USER} PGPASSWORD=${POSTGRES_PASSWORD} pg_isready -h localhost -p 5432 -d ${POSTGRES_DB}"
            initialDelaySeconds: 30 # Give Postgres time to start up
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          # Readiness probe to check if the database is ready to accept connections
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "PGUSER=${POSTGRES_USER} PGPASSWORD=${POSTGRES_PASSWORD} pg_isready -h localhost -p 5432 -d ${POSTGRES_DB}"
            initialDelaySeconds: 15 # Can be a bit shorter than liveness, as it focuses on connection readiness
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
      restartPolicy: Always