apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: train
  name: train
spec:
  ports:
    - name: "8021"
      port: 8021
      targetPort: 8021
  selector:
    io.kompose.service: train
