global:
  scrape_interval: 1s
  evaluation_interval: 15s

scrape_configs:
  - job_name: inference
    static_configs:
      - targets: ['inference:9091']

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']

  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']

  - job_name: 'train_container'
    static_configs:
      - targets: ['train_container:9100']
